package com.platform.model.lessons;
// Generated 2013-12-19 22:24:00 by Hibernate Tools 3.2.2.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;

import com.platform.model.menus.Menu;

/**
 * Vocabulary generated by hbm2java
 */
@Entity
@Table(name = "vocabulary", catalog = "platform")
public class Vocabulary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4279383992072049236L;
	private Integer id;
	private Theory theory;
	private String english;
	private String polish;
	private Integer poziom;
	private Integer lekcja;
	private WordTypes wordTypeId;
	private String picture;
	private String mp3;

	public Vocabulary() {
	}

	public Vocabulary(Theory theory, String english, String polish, Integer poziom,
			Integer lekcja, WordTypes wordTypeId, String picture, String mp3) {
		this.theory = theory;
		this.english = english;
		this.polish = polish;
		this.poziom = poziom;
		this.lekcja = lekcja;
		this.wordTypeId = wordTypeId;
		this.picture = picture;
		this.mp3 = mp3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "THEORY_ID")
	public Theory getTheory() {
		return this.theory;
	}

	public void setTheory(Theory theory) {
		this.theory = theory;
	}

	@Column(name = "ENGLISH", length = 100)
	@Length(max = 100)
	public String getEnglish() {
		return this.english;
	}

	public void setEnglish(String english) {
		this.english = english;
	}

	@Column(name = "POLISH", length = 100)
	@Length(max = 100)
	public String getPolish() {
		return this.polish;
	}

	public void setPolish(String polish) {
		this.polish = polish;
	}

	@Column(name = "Poziom")
	public Integer getPoziom() {
		return this.poziom;
	}

	public void setPoziom(Integer poziom) {
		this.poziom = poziom;
	}

	@Column(name = "lekcja")
	public Integer getLekcja() {
		return this.lekcja;
	}

	public void setLekcja(Integer lekcja) {
		this.lekcja = lekcja;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="WORD_TYPE_ID")
	public WordTypes getWordTypeId() {
		return this.wordTypeId;
	}

	public void setWordTypeId(WordTypes wordTypeId) {
		this.wordTypeId = wordTypeId;
	}

	@Column(name = "PICTURE", length = 100)
	@Length(max = 100)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "MP3", length = 100)
	@Length(max = 100)
	public String getMp3() {
		return this.mp3;
	}

	public void setMp3(String mp3) {
		this.mp3 = mp3;
	}

}
