package com.platform.model.exercises;
// Generated 2013-12-28 23:50:43 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name = "questions", catalog = "platform")
public class Questions implements java.io.Serializable {

	private Integer id;
	private String value;
	private Set<Exercises> exerciseses = new HashSet<Exercises>(0);

	public Questions() {
	}

	public Questions(String value, Set<Exercises> exerciseses) {
		this.value = value;
		this.exerciseses = exerciseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "VALUE", length = 200)
	@Length(max = 200)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "questions")
	public Set<Exercises> getExerciseses() {
		return this.exerciseses;
	}

	public void setExerciseses(Set<Exercises> exerciseses) {
		this.exerciseses = exerciseses;
	}

}
