package com.platform.model;
// Generated 2013-12-11 14:21:04 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "platform")
public class Menu implements java.io.Serializable {

	private Integer id;
	private Menu menu;
	private String name;
	private Set<Menu> menus = new HashSet<Menu>(0);
	private Set<Menu> menus_1 = new HashSet<Menu>(0);

	public Menu() {
	}

	public Menu(Menu menu, String name, Set<Menu> menus, Set<Menu> menus_1) {
		this.menu = menu;
		this.name = name;
		this.menus = menus;
		this.menus_1 = menus_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUPERIOR_ID")
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "NAME", length = 100)
	@Length(max = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<Menu> getMenus_1() {
		return this.menus_1;
	}

	public void setMenus_1(Set<Menu> menus_1) {
		this.menus_1 = menus_1;
	}

}
